### ISSUE TITLE
demo app , cannot find variable later

### ISSUE THREAD

**Issue by mikailcetinkaya** [Instawork/hyperview#61] opened 2019-04-07 17:28 UTC
Hi ;

In demo app , any  refresh part gives this error ::
(Like List with refresh )

ReferenceError: Can't find variable: later

This error is located at:
    in HvOption (at render/index.js:81)
    in RCTView (at View.js:44)
    in HvSelectSingle (at render/index.js:81)
    in RCTView (at View.js:44)
    in HyperScreen (at HyperviewScreen.js:70)
    in HyperviewScreen (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:483)
    in RCTView (at View.js:44)
    in AnimatedComponent (at screens.native.js:58)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:44)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:44)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:44)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:483)
    in RCTView (at View.js:44)
    in AnimatedComponent (at screens.native.js:58)
    in Screen (at StackViewCard.js:42)
    in Card (at createPointerEventsContainer.js:26)
    in Container (at StackViewLayout.js:507)
    in RCTView (at View.js:44)
    in ScreenContainer (at StackViewLayout.js:401)
    in RCTView (at View.js:44)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:49)
    in RCTView (at View.js:44)
    in Transitioner (at StackView.js:19)
    in StackView (at createNavigator.js:57)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at App.js:15)
    in App (at registerRootComponent.js:17)
    in RootErrorBoundary (at registerRootComponent.js:16)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

onUpdateFragment
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:163922:16
onUpdate
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:163734:34
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:167363:19
triggerSelectBehaviors
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:167354:32
componentDidUpdate
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:167412:38
commitLifeCycles
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:17582:46
commitAllLifeCycles
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:18736:29
invokeGuardedCallbackImpl
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:9710:21
invokeGuardedCallback
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:9796:42
commitRoot
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:18873:34
completeRoot
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20017:19
performWorkOnRoot
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:19957:27
performWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:19877:30
performSyncWork
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:19852:20
batchedUpdates$1
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:20053:28
batchedUpdates
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:11127:37
_receiveRootNodeIDEvent
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:11184:23
receiveTouches
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:11214:34
__callFunction
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3624:49
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3397:31
__guard
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3578:15
callFunctionReturnFlushedQueue
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fmikail%2Fhyperview%2Fdemo%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles.js:3396:21

**Comment by adamstep** [comment] 2019-04-10 15:08
Thanks for reporting, I'll look into this today.

**Comment by adamstep** [comment] 2019-04-21 22:10
Hi @mikailcetinkaya , I'm not able to reproduce this issue. I'm running the iOS simulator (iPhone X, iOS 12.1). "List with refresh" works properly without errors.

Can you share the details of your demo setup? Are you using iOS or Android? Simulator or real device?

**Comment by flochtililoch** [comment] 2019-04-29 07:57
Thanks for your bug report @mikailcetinkaya, this was fixed in #67. You can update to version 0.12.3.

**Closed by flochtililoch** 2019-04-29 07:57 UTC
